<a href="https://colab.research.google.com/github/vechi123/pandas_introex1/blob/main/pandas_intro_ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade 1 — Exercícios com os comandos básicos de pandas para EDA


Responda as perguntas abaixo no notebook (cada resposta deve ter ao menos uma célula de código que produza o output e, logo abaixo, uma célula de texto com a sua interpretação).

## 1) Carregue o dataset e mostre as primeiras 10 linhas.

In [16]:
import pandas as pd
df = pd.read_csv('/content/emendas.csv')
df.head(10)

/tmp/ipykernel_495/420280567.py:2: DtypeWarning: Columns (0,3,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/emendas.csv')

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
0,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,ALVORADA - RS,4300604,ALVORADA,4300000,...,1D73,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0000,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,"700000,00","0,00","0,00","0,00","690900,00","9100,00"
1,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,SANTA ISABEL DO PARÁ - PA,1506500,SANTA ISABEL DO PARÁ,1500000,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0000,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"487500,00","0,00","0,00","0,00","487500,00","0,00"
2,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,BARRA BONITA - SC,4202099,BARRA BONITA,4200000,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0000,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"100000,00","0,00","0,00","0,00","0,00","100000,00"
3,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,ARARAQUARA - SP,3503208,ARARAQUARA,3500000,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0000,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"243750,00","0,00","0,00","0,00","243750,00","0,00"
4,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,CAMPO LARGO - PR,4104204,CAMPO LARGO,4100000,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0000,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"1658333,94","0,00","0,00","0,00","527200,00","1131133,94"
5,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,CAMPINAS DO SUL - RS,4303806,CAMPINAS DO SUL,4300000,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0000,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"243750,00","0,00","0,00","0,00","0,00","243750,00"
6,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,MORENO - PE,2609402,MORENO,2600000,...,20RP,APOIO A INFRAESTRUTURA PARA A EDUCACAO BASICA,0000,INFRAESTRUTURA PARA A EDUCACAO BASICA - DESPES...,"700000,00","0,00","0,00","0,00","700000,00","0,00"
7,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,NOVA FLORESTA - PB,2510105,NOVA FLORESTA,2500000,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0000,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"278700,00","0,00","0,00","0,00","0,00","278700,00"
8,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,SANTIAGO DO SUL - SC,4215695,SANTIAGO DO SUL,4200000,...,20ZV,FOMENTO AO SETOR AGROPECUARIO,0000,FOMENTO AO SETOR AGROPECUARIO - DESPESAS DIVERSAS,"300000,00","300000,00","300000,00","0,00","0,00","0,00"
9,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,CIANORTE - PR,4105508,CIANORTE,4100000,...,1D73,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0000,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,"245850,00","0,00","0,00","0,00","0,00","245850,00"



```
# Isto está formatado como código
```

Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso	Código Município IBGE	Município	Código UF IBGE	...	Código Ação	Nome Ação	Código Plano Orçamentário	Nome Plano Orçamentário	Valor Empenhado	Valor Liquidado	Valor Pago	Valor Restos A Pagar Inscritos	Valor Restos A Pagar Cancelados	Valor Restos A Pagar Pagos.

## 2) Quantas linhas e colunas o dataset possui?

In [17]:
df.shape

(88596, 28)

n_linhas e n_colunas

## 3) Liste os nomes das colunas e descreva brevemente o que você entende que cada coluna representa.

In [18]:
df.dtypes

Código da Emenda                      object
Ano da Emenda                          int64
Tipo de Emenda                        object
Código do Autor da Emenda             object
Nome do Autor da Emenda               object
Número da emenda                      object
Localidade de aplicação do recurso    object
Código Município IBGE                 object
Município                             object
Código UF IBGE                         int64
UF                                    object
Região                                object
Código Função                         object
Nome Função                           object
Código Subfunção                      object
Nome Subfunção                        object
Código Programa                       object
Nome Programa                         object
Código Ação                           object
Nome Ação                             object
Código Plano Orçamentário             object
Nome Plano Orçamentário               object
Valor Empenhado                       object
Valor Liquidado                       object
Valor Pago                            object
Valor Restos A Pagar Inscritos        object
Valor Restos A Pagar Cancelados       object
Valor Restos A Pagar Pagos            object
dtype: object

cada coluna representa uma função: Código da Emenda, Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,UF, Região,Código Função,Nome Função,Código Subfunção Nome Subfunção	object
Código Programa
Nome Programa
Código Ação
Nome Ação
Código Plano Orçamentário
Nome Plano Orçamentário
Valor Empenhado
Valor Liquidado
Valor Pago
Valor Restos A Pagar Inscritos
Valor Restos A Pagar Cancelados
Valor Restos A Pagar Pagos

## 4) Existem valores nulos? quantos?

In [19]:
nulos = df.isnull().sum()
print(nulos)

Código da Emenda                      0
Ano da Emenda                         0
Tipo de Emenda                        0
Código do Autor da Emenda             0
Nome do Autor da Emenda               0
Número da emenda                      0
Localidade de aplicação do recurso    0
Código Município IBGE                 0
Município                             0
Código UF IBGE                        0
UF                                    0
Região                                0
Código Função                         0
Nome Função                           0
Código Subfunção                      0
Nome Subfunção                        0
Código Programa                       0
Nome Programa                         0
Código Ação                           0
Nome Ação                             0
Código Plano Orçamentário             0
Nome Plano Orçamentário               0
Valor Empenhado                       0
Valor Liquidado                       0
Valor Pago                            0
Valor Restos A Pagar Inscritos        0
Valor Restos A Pagar Cancelados       0
Valor Restos A Pagar Pagos            0
dtype: int64

## 5) Mostre os tipos das variáveis (se int, string, boolean, float...) e analise se alguma variável parece ter o tipo errado. Faça isso da maneira mais objetiva e otimizada possível.

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88596 entries, 0 to 88595
Data columns (total 28 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Código da Emenda                    88596 non-null  object
 1   Ano da Emenda                       88596 non-null  int64
 2   Tipo de Emenda                      88596 non-null  object
 3   Código do Autor da Emenda           88596 non-null  object
 4   Nome do Autor da Emenda             88596 non-null  object
 5   Número da emenda                    88596 non-null  object
 6   Localidade de aplicação do recurso  88596 non-null  object
 7   Código Município IBGE               88596 non-null  object
 8   Município                           88596 non-null  object
 9   Código UF IBGE                      88596 non-null  int64
 10  UF                                  88596 non-null  object
 11  Região                              88596 non-null  object
 12  Código Função                       88596 non-null  object
 13  Nome Função                         88596 non-null  object
 14  Código Subfunção                    88596 non-null  object
 15  Nome Subfunção                      88596 non-null  object
 16  Código Programa                     88596 non-null  object
 17  Nome Programa                       88596 non-null  object
 18  Código Ação                         88596 non-null  object
 19  Nome Ação                           88596 non-null  object
 20  Código Plano Orçamentário           88596 non-null  object
 21  Nome Plano Orçamentário             88596 non-null  object
 22  Valor Empenhado                     88596 non-null  object
 23  Valor Liquidado                     88596 non-null  object
 24  Valor Pago                          88596 non-null  object
 25  Valor Restos A Pagar Inscritos      88596 non-null  object
 26  Valor Restos A Pagar Cancelados     88596 non-null  object
 27  Valor Restos A Pagar Pagos          88596 non-null  object
dtypes: int64(2), object(26)
memory usage: 18.9+ MB

Se alguma coluna estiver com o tipo errado, escreva abaixo qual é e por que isso pode atrapalhar análises.

**Dica:** Se alguma variável tiver no tipo o nome "object", isso se refere a texto.

## 6) Usando a coluna `Ano da Emenda` como base, descubra até que ano o dataset está atualizado (mostre as 8 primeiras linhas do df ordenado desc).

In [21]:
df_ordenado = df.sort_values(by='Ano da Emenda', ascending=False)
print(df_ordenado.head(8))

      Código da Emenda  Ano da Emenda  \
88564     202541820003           2025
88578     202544940001           2025
88595     202544840009           2025
88594     202544840008           2025
88577     202541820017           2025
88576     202541820016           2025
88575     202541820015           2025
88574     202541820014           2025

                                          Tipo de Emenda  \
88564       Emenda Individual - Transferências Especiais
88578  Emenda Individual - Transferências com Finalid...
88595  Emenda Individual - Transferências com Finalid...
88594  Emenda Individual - Transferências com Finalid...
88577  Emenda Individual - Transferências com Finalid...
88576  Emenda Individual - Transferências com Finalid...
88575  Emenda Individual - Transferências com Finalid...
88574  Emenda Individual - Transferências com Finalid...

      Código do Autor da Emenda Nome do Autor da Emenda Número da emenda  \
88564                      4182        ZEQUINHA MARINHO                3
88578                      4494         ZEZINHO BARBARY                1
88595                      4484                   ZUCCO                9
88594                      4484                   ZUCCO                8
88577                      4182        ZEQUINHA MARINHO               17
88576                      4182        ZEQUINHA MARINHO               16
88575                      4182        ZEQUINHA MARINHO               15
88574                      4182        ZEQUINHA MARINHO               14

      Localidade de aplicação do recurso Código Município IBGE  \
88564                           MÚLTIPLO        Sem informação
88578                           Nacional        Sem informação
88595                           MÚLTIPLO        Sem informação
88594                           Nacional        Sem informação
88577                      REDENÇÃO - PA               1506138
88576                          PARÁ (UF)        Sem informação
88575                          PARÁ (UF)        Sem informação
88574                           MÚLTIPLO        Sem informação

            Município  Código UF IBGE  ... Código Ação  \
88564        Múltiplo         1500000  ...        0EC2
88578  Sem informação              -1  ...        2726
88595        Múltiplo         4300000  ...        20JP
88594  Sem informação              -1  ...        2723
88577        REDENÇÃO         1500000  ...        219G
88576  Sem informação         1500000  ...        8535
88575  Sem informação         1500000  ...        20Z1
88574        Múltiplo         1500000  ...        00SL

                                               Nome Ação  \
88564                           TRANSFERENCIAS ESPECIAIS
88578  PREVENCAO E REPRESSAO AO TRAFICO ILICITO DE DR...
88595  DESENVOLVIMENTO DE ATIVIDADES E APOIO A PROGRA...
88594  POLICIAMENTO, FISCALIZACAO, ENFRENTAMENTO A CR...
88577  ESTRUTURACAO DA REDE DE SERVICOS E FORTALECIME...
88576  ESTRUTURACAO DE UNIDADES DE ATENCAO ESPECIALIZ...
88575  QUALIFICACAO SOCIAL E PROFISSIONAL DE TRABALHA...
88574  APOIO A IMPLANTACAO E MODERNIZACAO DE INFRAEST...

      Código Plano Orçamentário  \
88564                      0000
88578                      0000
88595                      0000
88594                      0000
88577                      0000
88576                      0000
88575                      0000
88574                      0000

                                 Nome Plano Orçamentário Valor Empenhado  \
88564                           TRANSFERENCIAS ESPECIAIS     12161000,00
88578  PREVENCAO E REPRESSAO AO TRAFICO ILICITO DE DR...       478233,30
88595  DESENVOLVIMENTO DE ATIVIDADES E APOIO A PROGRA...      1800000,00
88594  POLICIAMENTO, FISCALIZACAO, ENFRENTAMENTO A CR...       497151,34
88577  ESTRUTURACAO DA REDE DE SERVICOS E FORTALECIME...       370000,00
88576  ESTRUTURACAO DE UNIDADES DE ATENCAO ESPECIALIZ...       600000,00
88575  QUALIFICACAO SOCIAL E PROFISSIONAL DE TRABALHA...       500000,00
88574  APOIO A IMPLANTACAO E MODERNIZACAO DE INFRAEST...       500000,00

      Valor Liquidado   Valor Pago Valor Restos A Pagar Inscritos  \
88564     12039390,00  12039390,00                           0,00
88578            0,00         0,00                           0,00
88595        36000,00         0,00                           0,00
88594            0,00         0,00                           0,00
88577       370000,00    370000,00                           0,00
88576            0,00         0,00                           0,00
88575            0,00         0,00                           0,00
88574            0,00         0,00                           0,00

      Valor Restos A Pagar Cancelados Valor Restos A Pagar Pagos
88564                            0,00                       0,00
88578                            0,00                       0,00
88595                            0,00                       0,00
88594                            0,00                       0,00
88577                            0,00                       0,00
88576                            0,00                       0,00
88575                            0,00                       0,00
88574                            0,00                       0,00

[8 rows x 28 columns]

Explique: qual é o ano mais recente presente no dataset?
Resposta: 2025

## 7) execute um  `describe()` e explique uma conclusão simples que você consegue tirar a partir das estatísticas (se algumas colunas deveriam aparecer no describe mas não aparecem, indique o motivo que você acredita que esteja causando esse problema).

In [22]:
df.describe()

       Ano da Emenda  Código UF IBGE
count   88596.000000    8.859600e+04
mean     2019.155109    2.943594e+06
std         3.409323    1.264884e+06
min      2014.000000   -1.400000e+01
25%      2016.000000    2.300000e+06
50%      2019.000000    3.100000e+06
75%      2022.000000    3.500000e+06
max      2025.000000    5.300000e+06

## 8) Mostre as últimas 5 linhas do dataset e escreva se a última linha parece completa (sem muitos nulos) ou não.

In [23]:
df.tail(5)

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
88591,202544840005,2025,Emenda Individual - Transferências Especiais,4484,ZUCCO,5,MÚLTIPLO,Sem informação,Múltiplo,4300000,...,0EC2,TRANSFERENCIAS ESPECIAIS,0000,TRANSFERENCIAS ESPECIAIS,"12307991,08","12184912,08","12184912,08","0,00","0,00","0,00"
88592,202544840006,2025,Emenda Individual - Transferências com Finalid...,4484,ZUCCO,6,MÚLTIPLO,Sem informação,Múltiplo,4300000,...,20ZV,FOMENTO AO SETOR AGROPECUARIO,0000,FOMENTO AO SETOR AGROPECUARIO - DESPESAS DIVERSAS,"988649,90","25592,00","25592,00","0,00","0,00","0,00"
88593,202544840007,2025,Emenda Individual - Transferências com Finalid...,4484,ZUCCO,7,Nacional,Sem informação,Sem informação,-1,...,2000,ADMINISTRACAO DA UNIDADE,0000,ADMINISTRACAO DA UNIDADE - DESPESAS DIVERSAS,"999914,73","155246,57","149728,52","0,00","0,00","0,00"
88594,202544840008,2025,Emenda Individual - Transferências com Finalid...,4484,ZUCCO,8,Nacional,Sem informação,Sem informação,-1,...,2723,"POLICIAMENTO, FISCALIZACAO, ENFRENTAMENTO A CR...",0000,"POLICIAMENTO, FISCALIZACAO, ENFRENTAMENTO A CR...","497151,34","0,00","0,00","0,00","0,00","0,00"
88595,202544840009,2025,Emenda Individual - Transferências com Finalid...,4484,ZUCCO,9,MÚLTIPLO,Sem informação,Múltiplo,4300000,...,20JP,DESENVOLVIMENTO DE ATIVIDADES E APOIO A PROGRA...,0000,DESENVOLVIMENTO DE ATIVIDADES E APOIO A PROGRA...,"1800000,00","36000,00","0,00","0,00","0,00","0,00"

Interprete a completude da última linha.

## 9) existem valores duplicados no dataframe? Caso positivo, quantos?

In [24]:
total_duplicates = df.duplicated().sum()
print(total_duplicates)

0